/// Flutter icons MyWineIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyWineIcon
///      fonts:
///       - asset: fonts/MyWineIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyWineIcon {
  MyWineIcon._();

  static const _kFontFam = 'MyWineIcon';

  static const IconData italian_wine_bottle_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam);
}
